# docker-compose.yml
version: '3.8'

services:
  # --- Redis Servisi ---
  redis:
    image: redis:alpine
    container_name: rovits-redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  # --- API Servisi ---
  api:
    container_name: rovits-api
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NODE_ENV: production
    # GÜNCELLENDİ: Redis sağlıklı (healthy) olmadan başlama
    depends_on:
      redis:
        condition: service_healthy

  # --- Worker Servisi ---
  worker:
    container_name: rovits-worker
    build:
      context: .
      dockerfile: Dockerfile.worker
    restart: always
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NODE_ENV: production
    depends_on:
      redis:
        condition: service_healthy

# --- Volumes ---
volumes:
  redis_data: